spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/switch_03_11_2025_USER
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
   tracing:
    enabled: true
    sampling:
      probability: 1.0   # Capture 100% of requests
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,env,beans,trace
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      UserWithDepartment:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      UserWithDepartment:
        registerHealthIndicator: true
        maxAttempts: 5
        waitDuration: 10s
  ratelimiter:
    instances:
      UserWithDepartment:
          registerHealthIndicator: true
          limitForPeriod: 10
          limitRefreshPeriod: 10s
          timeoutDuration: 3s
